FROM debian:bullseye

LABEL maintainer="pricea35@cardiff.ac.uk" \
software="picard" \
software.version="2.27.5" \
about.summary="Tools for manipulating SAM/BAM/CRAM and VCF files" \
about.home="https://github.com/broadinstitute/picard"

ENV picard_version=2.27.5

ENV PACKAGES="curl wget parallel openjdk-11-jdk"

RUN apt-get update \
&& apt-get install -y $PACKAGES \
&& wget https://github.com/broadinstitute/picard/releases/download/${picard_version}/picard.jar -O /opt/picard.jar \
&& echo "#!/bin/bash" >> /usr/local/bin/picard \
&& echo 'java -jar /opt/picard.jar $@' >> /usr/local/bin/picard \
&& chmod +x /usr/local/bin/picard

WORKDIR /opt

ENV PATH=${PATH}:/opt

ENV PICARD_JAR=/opt/picard.jar

CMD ["java", "-jar", "picard.jar", "-h"]
