FROM debian:bullseye

LABEL maintainer="pricea35@cardiff.ac.uk" \
software="iva" \
software.version="v1.0.9" \
about.summary="de novo virus assembler for Illumina paired reads" \
about.home="https://github.com/sanger-pathogens/iva"

ENV iva_version=1.0.9 \
kmc_version=3.2.1 \
mummer_version=3.23 \
htslib_version=1.16 \
samtools_version=1.16.1 \
smalt_version=0.7.6 \
trimmomatic_version=0.38 \
kraken2_version=2.1.2

ENV PACKAGES="wget curl parallel build-essential zlib1g-dev libncurses-dev libbz2-dev liblzma-dev libcurl4-openssl-dev libfindbin-libs-perl rsync unzip ncbi-blast+ r-base-core bioperl openjdk-11-jre locales locales-all smalt"

ENV PYTHON="python3 python3-pip"

RUN apt-get update \
&& apt-get install -y $PACKAGES $PYTHON

RUN wget -O KMC.tar.gz https://github.com/refresh-bio/KMC/releases/download/v${kmc_version}/KMC${kmc_version}.linux.tar.gz \
&& tar -xzf KMC.tar.gz -C /usr/local/bin

RUN wget https://downloads.sourceforge.net/project/mummer/mummer/${mummer_version}/MUMmer${mummer_version}.tar.gz -O /usr/local/bin/MUMmer${mummer_version}.tar.gz \
&& cd /usr/local/bin \
&& tar -xzf MUMmer${mummer_version}.tar.gz \
&& cd MUMmer${mummer_version} \
&& make \
&& make install \
&& cd /

RUN curl -fsSL https://github.com/samtools/samtools/archive/${samtools_version}.tar.gz | tar -xz \
&& curl -fsSL https://github.com/samtools/htslib/releases/download/${htslib_version}/htslib-${htslib_version}.tar.bz2 | tar -xj \
&& make -C samtools-${samtools_version} -j HTSDIR=../htslib-${htslib_version} \
&& make -C samtools-${samtools_version} -j HTSDIR=../htslib-${htslib_version} prefix=/usr/local install \
&& rm -r samtools-${samtools_version} \
&& rm -r htslib-${htslib_version}

RUN wget http://www.usadellab.org/cms/uploads/supplementary/Trimmomatic/Trimmomatic-${trimmomatic_version}.zip \
&& unzip Trimmomatic-${trimmomatic_version}.zip \
&& echo "#!/bin/bash" >> trimmomatic \
&& echo 'java -jar /Trimmomatic-${trimmomatic_version}/trimmomatic-${trimmomatic_version}.jar $@' >> /usr/local/bin/trimmomatic \
&& chmod +x /usr/local/bin/trimmomatic

RUN wget -O kraken2-${kraken2_version}.tar.gz https://github.com/DerrickWood/kraken2/archive/refs/tags/v${kraken2_version}.tar.gz \
&& tar -xzf kraken2-${kraken2_version}.tar.gz \
&& rm kraken2-${kraken2_version}.tar.gz \
&& cd kraken2-${kraken2_version} \
&& ./install_kraken2.sh /usr/local/bin \
&& cd ..

RUN pip3 install iva==${iva_version}

RUN locale-gen en_GB.UTF-8

ENV LANG en_GB.UTF-8 \
LANGUAGE en_GB:en \
LC_ALL en_GB.UTF-8

ENV PATH ${PATH}:/usr/local/bin/MUMmer${mummer_version}:/usr/local/bin/KMC${kmc_version}.linux

CMD ["iva", "--help"]
