FROM debian:bullseye

LABEL maintainer="pricea35@cardiff.ac.uk" \
software="cutadapt" \
software.version="4.1" \
about.summary="finds and removes adapter sequences" \
about.home="https://pypi.org/project/cutadapt/"

ENV cutadapt_version=4.1

ENV PACKAGES="curl wget parallel python3 python3-pip"

RUN apt-get update \
&& apt-get install -y $PACKAGES \
&& python3 -m pip install cutadapt==${cutadapt_version}

CMD ["cutadapt", "--help"]
