FROM debian:bullseye

LABEL maintainer="pricea35@cardiff.ac.uk" \
software="metabat" \
software.version="2.15" \
about.summary="Metagenome binning using metabat2" \
about.home="https://bitbucket.org/berkeleylab/metabat/"

ENV metabat2_version=2.15

ENV PACKAGES="build-essential git autoconf libboost-all-dev cmake libgomp1 curl wget parallel libncurses5-dev zlib1g-dev" \
PYTHON="python3 python3-pip"

RUN apt-get update \
&& apt-get install -y $PACKAGES $PYTHON \
&& curl -fsSL https://bitbucket.org/berkeleylab/metabat/get/v${metabat2_version}.tar.gz | tar -xz \
&& cd berkeleylab-metabat-* \
&& mkdir build \
&& cd build \
&& cmake -DCMAKE_INSTALL_PREFIX=/usr/local .. \
&& make \
&& make install \
&& cd .. \
&& rm -rf build \
&& cd /

CMD ["metabat2", "--help"]
