FROM debian:bullseye

LABEL maintainer="pricea35@cardiff.ac.uk" \
software="krakenuniq" \
software.version="0.7.2" \
about.summary="Metagenomic classification with unique kmers using krakenuniq" \
about.home="https://github.com/fbreitwieser/krakenuniq"

ENV krakenuniq_version=0.7.2

ENV PACKAGES="curl wget parallel make g++ git zlib1g zlib1g-dev libbz2-dev libgomp1"

RUN apt-get update \
&& apt-get -y install $PACKAGES \
&& curl -fsSL "https://github.com/fbreitwieser/krakenuniq/archive/v${krakenuniq_version}.tar.gz" | tar xz \
&& cd krakenuniq-${krakenuniq_version} \
&& ./install_krakenuniq.sh -j /usr/local/bin \
&& cd .. && rm -rf krakenuniq

CMD ["krakenuniq"]
